### ISSUE TITLE
Create Service and Dao layer

### ISSUE THREAD

**Issue by MarinTrpenovski** [WORK-MENTOR/Spring-Rest#2]
Create service and dao layer in project.
Connect to Database using JDBC and Singleton pattern for database connection.
Create beans for each of the entities that is needed. 

Link dao classes to service layer using Autowire anotation. Not to create instance to DAO classes from service classes (like UserDao user = new UserDao()). Not using this approach.

Pay attention on method names, variables names and don't leave commented code. 

Please start work on this issue

**Comment by AngelaM123** [comment]
Created service and DAO layer used the Singleton pattern with JDBC connection and created beans for the entities ,also used the different approach that was required ,used @Autowired, @Repository and @Service annotations instead of creating an instance ate the end tried to put names that are appropriate. After checking the code let me know for further corrections if needed

**Comment by MarinTrpenovski** [comment]
Code looks good;
In ProfesorDAO add one line empty in order to be consistent with other interfaces syntax.
In FacultyDAOImpl in delete method have defined variable that is not used. Please clean code. 
In ProfesorDaoImpl in delete method have unused variables, please clean code.
In UniversityDAOImpl in found commented code please remove it.
In SubjectDAOImpl there is commented code please remove it.
![image](https://user-images.githubusercontent.com/27773018/216539039-9223144f-de28-4165-85e5-29d99d39faa6.png)
Is this coded needed ? I found in all save methods in entities in DAOImpl classes.

In SingletonConnection class remove DB credentials and configuration properties in constants package in DBConstant class. 

@AngelaM123 Please take a look at this.

**Comment by MarinTrpenovski** [comment]
@AngelaM123 Is this issue also resolve by PR https://github.com/WORK-MENTOR/Spring-Rest/pull/17

As I can see notes from last comments are not resolved.

Please take a look , so we can close this issue too.

**Comment by AngelaM123** [comment]
I edited DAOimpl classes as well as Singleton and DBConstants class check and comment for other possible changes

**Comment by MarinTrpenovski** [comment]
Code looks good now @AngelaM123 Closing this issue.
