### ISSUE TITLE
Connect layers in project

### ISSUE THREAD

**Issue by MarinTrpenovski** [WORK-MENTOR/Spring-Rest#3]
Integrate service layer in REST controllers.
Now each of the endpoints should return data from Database.

When link service layer methods use @autowire anotation to use service's classes in controllers.

REST endpoints should return ResponseEntity object with appropriate status codes for each of the CRUD operations. (https://www.baeldung.com/spring-response-entity) 

You can start work on this issue

**Comment by AngelaM123** [comment]
have manage to connect layer in the project and commit the newest versions of the controllers after checking let me know for more corrections if something is missing

**Comment by MarinTrpenovski** [comment]
Just remove this code I think its not needed to have init() method. I was just for testing purposes before connect to Database. Now when you are connected to Database you can remove method and all logic related with manipulation with that Array. 
@AngelaM123 Please take a look at this issue. 
![image](https://user-images.githubusercontent.com/27773018/216809717-eaaeaed8-6f71-4340-9dd7-689e568526c5.png)
![image](https://user-images.githubusercontent.com/27773018/216809920-872d28f2-7ec0-4116-8fe0-a11c20eafd9c.png)

If you want to keep it, in case to remember it you can leave it in one of the Entities, but remove logic from REST endpoint when invoke them.

**Comment by AngelaM123** [comment]
I have edited the controller classes I have deleted the init() method and other codes related to that logic

**Comment by MarinTrpenovski** [comment]
Code looks good @AngelaM123 closing this issue.
